
import Navigation from "@/components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Demo Web",
  description: "Generated by create next app",
  keywords: "next,react,app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-color1 min-h-screen font-poppins tracking-wide">
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
